# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('armor_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Being',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('health', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('armor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Armor')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('min_att_value', models.IntegerField()),
                ('max_att_value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='being',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Weapon'),
        ),
    ]
