# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_wall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='being',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Armor'),
        ),
        migrations.AlterField(
            model_name='being',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Weapon'),
        ),
    ]
