# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='being',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
